-- 인코딩 이슈
sqlplus '/as sysdba'		
SHUTDOWN IMMEDIATE;		
STARTUP MOUNT;		
ALTER SYSTEM ENABLE RESTRICTED SESSION;		
ALTER SYSTEM SET JOB_QUEUE_PROCESSES=0;		
ALTER SYSTEM SET AQ_TM_PROCESSES=0;		
ALTER DATABASE OPEN;		
ALTER DATABASE CHARACTER SET INTERNAL_USE AL32UTF8;		
SHUTDOWN IMMEDIATE;		
STARTUP;
